import {
  brics,
  brics2,
  cardiff,
  brixx1,
  brixx2,
  brixx3,
  brixx4,
  brixx5,
  brixx6,
  brixx7,
  brixx8,
  brixx9,
  brixx10,
  brixx11,
  brixx12,
  brixx13,
  brixx14,
  brixx15,
  calisto1,
  calisto2,
  calisto3,
  calisto4,
  calisto5,
  calisto6,
  calisto7,
  calisto8,
  calisto9,
  calisto10,
  calisto11,
  calisto12,
  calisto13,
  calisto14,
  ore_ofe1,
  ore_ofe2,
  ore_ofe3,
  ore_ofe4,
  ore_ofe5,
  mc_allen1,
  mc_allen2,
  mc_allen3,
  mc_allen4,
  mc_allen5,
  mc_allen6,
  mc_allen7,
  mc_allen8,
  mc_allen9,
  mc_allen10,
  mc_allen11,
  mc_allen12,
  mc_allen13,
  mc_allen14,
  mc_allen15,
  mc_allen16,
  mc_allen17,
  mc_allen18,
  mc_allen19,
  mc_allen20,
  mc_allen21,
  mc_allen22,
  mc_allen23,
} from "@/utils/image";

export const projects = [
//   {
//     thumbnail: brixx1,
//     images: [
//       brixx1,
//       brixx2,
//       brixx3,
//       brixx4,
//       brixx5,
//       brixx6,
//       brixx7,
//       brixx8,
//       brixx9,
//       brixx10,
//       brixx11,
//       brixx12,
//       brixx13,
//       brixx14,
//       brixx15,
//     ],
//     label: "The Brixx",
//   },
  {
    thumbnail: ore_ofe5,
    images: [ore_ofe1, ore_ofe2, ore_ofe3, ore_ofe4, ore_ofe5],
    label: "Ore Ofe Residence",
  },
  {
    thumbnail: calisto1,
    images: [
      calisto1,
      calisto2,
      calisto3,
      calisto4,
      calisto5,
      calisto6,
      calisto7,
      calisto8,
      calisto9,
      calisto10,
      calisto11,
      calisto12,
      calisto13,
      calisto14,
    ],
    label: "Calisto Phase One",
  },
  {
    thumbnail: mc_allen1,
    images: [
      mc_allen1,
      mc_allen2,
      mc_allen3,
      mc_allen4,
      mc_allen5,
      mc_allen6,
      mc_allen7,
      mc_allen8,
      mc_allen9,
      mc_allen10,
      mc_allen11,
      mc_allen12,
      mc_allen13,
      mc_allen14,
      mc_allen15,
      mc_allen16,
      mc_allen17,
      mc_allen18,
      mc_allen19,
      mc_allen20,
      mc_allen21,
      mc_allen22,
      mc_allen23,
    ],
    label: "Mc Allen Redidence",
  },
];
